[package]
name = "blockwise_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmem = "0.1.1"
stringreader = "0.1.1"
